debug: false

logging:
  level:
    org.springframework: warn
    org.vaulttec: info

sync:
  emailDomain: dekager.dekabank.intern
  rate: 3000

keycloak:
  serverUrl: http://torstens-macbook-pro.local:8080/auth
  clientSecret: 47cae011-870e-4727-a5f0-1f92323bf829

gitlab:
  serverUrl: http://torstens-macbook-pro.local:8083
  personalAccessToken: d9FPuic1fFd-gzNvpmw4

mattermost:
  serverUrl: http://torstens-macbook-pro.local:8084
  personalAccessToken: pdybh3z18bbb9jutubwhtyt9te
