server.port: 8081

management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - auditevents


keycloak:
  serverUrl: 
  clientSecret: 

gitlab:
  serverUrl: 
  personalAccessToken: 

mattermost:
  serverUrl: 
  personalAccessToken: 
      