spring:
  application:
    name: idm-sync
  mvc:
    contentnegotiation:
      media-types:
        json: application/json
        yaml: application/yaml
        csv: text/csv
      favor-path-extension: true
    pathmatch:
      use-registered-suffix-pattern: true
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  main:
    banner-mode: "off"

logging:
  file:
    max-history: 10
  level:
    org.springframework: info
    org.vaulttec: info

proxy:
  host:
  port: 3128

sync:
  emailDomain: acme.com
  removeRequiredActions: true
  rate: 600000  # 10 min
  auditEventRepositoryCapacity: 1000
  enabledApps:
    - "*"

idp:
  factory: org.vaulttec.idm.sync.idp.keycloak.KeycloakFactory
  config:
    serverUrl: ${keycloak.serverUrl}
    realm: sso
    client:
      id: idm-sync
      secret: ${keycloak.clientSecret}
    perPage: 100

apps:
  - factory: org.vaulttec.idm.sync.app.gitlab.GitLabFactory
    config:
      serverUrl: ${gitlab.serverUrl}
      personalAccessToken: ${gitlab.personalAccessToken}
      group:
        search: "%_GIT_%"
        regExp: .*_GIT_(?<groupPath>\w*)_(?<permission>\w*)
      sync:
        excludedUsers: root, ghost, gladmin
        removeProjectMembers: true
      provider:
        name: ${gitlab.providerName}
        uidAttribute: ${gitlab.providerUidAttribute}
      perPage: 100
  - factory: org.vaulttec.idm.sync.app.mattermost.MattermostFactory
    config:
      serverUrl: ${mattermost.serverUrl}
      personalAccessToken: ${mattermost.personalAccessToken}
      group:
        search: "%_GIT_%"
        regExp: .*_GIT_(?<teamName>\w*)_(?<teamAdmin>Maintainer)?.*
      sync:
        excludedUsers: mmadmin
      auth:
        serviceName: gitlab
        uidAttribute: GITLAB_USER_ID
      perPage: 100

api:
  csvSeparator: ";"
