management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

idp:
  factory: org.vaulttec.idm.sync.idp.keycloak.KeycloakFactory
  config:
    serverUrl: 
    realm: sso
    client:
      id: idm-sync
      secret: 
    perPage: 100

apps:
  - factory: org.vaulttec.idm.sync.app.gitlab.GitLabFactory
    config:
      serverUrl: 
      privateToken: 
      group:
        search: "%_GIT_%"
        regExp: .*_GIT_(?<groupPath>\w*)_(?<permission>\w*)
      sync:
        excludedUsers: root, ghost
        removeProjectMembers: true
      provider:
        name: ldapmain
        uidAttribute: LDAP_ENTRY_DN
      perPage: 100
