management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
        - auditevents

sync:
  emailDomain: ${EMAIL_DOMAIN}

keycloak:
  serverUrl: ${KEYCLOAK_SERVER_URL}
  clientSecret: ${KEYCLOAK_CLIENT_SECRET}

gitlab:
  serverUrl: ${GITLAB_SERVER_URL}
  personalAccessToken: ${GITLAB_PERSONAL_ACCESS_TOKEN}

mattermost:
  serverUrl: ${MATTERMOST_SERVER_URL}
  personalAccessToken: ${MATTERMOST_PERSONAL_ACCESS_TOKEN}
